### ISSUE TITLE
Hi how can we calculate the weather conditions by using this.How it could be useful?

### ISSUE THREAD

**Issue by rohith231** [rwev/leaflet-radar#3]
Hi how can we calculate the weather conditions by using this.How it could be useful?

**Comment by rwev** [comment]
This plugin loads weather radar images only; you'll have to find another source / API for numeric weather data and predictions.

**Comment by rohith231** [comment]
hi please tell what is the use of this model

**Comment by rohith231** [comment]
What is the green and yellow color represent in this radar

**Comment by rwev** [comment]
https://en.wikipedia.org/wiki/Weather_radar#Data_types
